objects/Academic_Year__c.object
<CustomObject><fields>
        <fullName>CurrentAcademicYrEndDate__c</fullName>
        <description>currentAcademicYearEndDate</description>
        <inlineHelpText>currentAcademicYearEndDate</inlineHelpText>
        <label>CurrentAcademicYrEndDate</label>
        <type>Date</type>
    </fields><fields>
        <fullName>CurrentAcademicYrStartDate__c</fullName>
        <description>currentAcademicYearStartDate</description>
        <inlineHelpText>currentAcademicYearStartDate</inlineHelpText>
        <label>CurrentAcademicYrStartDate</label>
        <type>Date</type>
    </fields><customSettingsType>List</customSettingsType><description>Academic Year</description><enableFeeds>false</enableFeeds><label>Academic Year</label><visibility>Public</visibility></CustomObject>

objects/Account.object
<CustomObject><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>8</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Addendum__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Addendum</label><nameField>
        <label>Addenda Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Addenda</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/BenchMar_AtciontStep__c.object
<CustomObject><fields>
        <fullName>Improvement_Action_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Improvement Action Step</label>
        <referenceTo>Improvement_Action_Step__c</referenceTo>
        <relationshipLabel>BenchMar_ActiontSteps</relationshipLabel>
        <relationshipName>BenchMar_ActiontSteps</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>BenchMar_ActiontStep</label><nameField>
        <displayFormat>AB-{0000}</displayFormat>
        <label>BenchMar_AtciontStep Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>BenchMar_ActiontSteps</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Implementation_Benchmark__c.object
<CustomObject><fields>
        <fullName>Major_Improvement_Strategy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Major Improvement Strategy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Major Improvement Strategy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Implementation Benchmarks</relationshipLabel>
        <relationshipName>Implementation_Benchmarks</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <picklist>
            <picklistValues>
                <fullName>This School Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Next School Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Implementation Benchmarks</relationshipLabel>
        <relationshipName>Implementation_Benchmarks</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Implementation Benchmark</label><nameField>
        <label>Implementation Benchmark Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Implementation Benchmarks</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Improvement_Action_Step__c.object
<CustomObject><fields>
        <fullName>Root_Cause_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Root Cause</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Improvement Action Steps (Root Cause 1)</relationshipLabel>
        <relationshipName>Improvement_Action_Steps1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <picklist>
            <picklistValues>
                <fullName>This School Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Next School Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Improvement Action Steps</relationshipLabel>
        <relationshipName>Improvement_Action_Steps</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Improvement Action Step</label><nameField>
        <label>Action Step Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Improvement Action Steps</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Performance_Indicator_Notable_Trends__c.object
<CustomObject><fields>
        <fullName>Priority_Performance_Challenge_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Priority Performance Challenge 1</label>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Performance Indicator Notable Trends (Priority Performance Challenge 1)</relationshipLabel>
        <relationshipName>Performance_Indicator_Notable_Trends</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Root_Cause_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause 1</label>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Performance Indicator Notable Trends (Root Cause 1)</relationshipLabel>
        <relationshipName>Performance_Indicator_Notable_TrendsHERJ</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Performance Indicator Notable Trends</relationshipLabel>
        <relationshipName>Performance_Indicator_Notable_Trends</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Performance Indicator Notable Trend</label><nameField>
        <displayFormat>PINNP-{0000}</displayFormat>
        <label>Performance Indicator Notable Trends Nam</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Performance Indicator Notable Trends</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Performance_Indicator_Targets__c.object
<CustomObject><fields>
        <fullName>Priority_Performance_Challenge_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Priority Performance Challenge 1</label>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Performance Indicator Targets</relationshipLabel>
        <relationshipName>Performance_Indicator_Targets</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Performance Indicator Targets</relationshipLabel>
        <relationshipName>Performance_Indicator_Targets</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Performance Indicator Targets</label><nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Performance Indicator Targets Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Performance Indicator Targets</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>ACADEMIC_YEAR__c</fullName>
        <label>Academic Year</label>
        <length>6</length>
        <type>Text</type>
    </fields><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Is_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for versioning</description>
        <label>Is Version</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <label>Academic Year</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Contact__c.object
<CustomObject><fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>UIP Contacts</relationshipLabel>
        <relationshipName>UIP_Contacts</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Junction object between UIP and contacts for Section II of the UIP.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Contact</label><nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>UIP Contact Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>UIP Contacts</pluralLabel><sharingModel>Private</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Element__c.object
<CustomObject><fields>
        <fullName>Challenge_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Challenge 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Challenge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Root Cause</relationshipLabel>
        <relationshipName>Root_Cause</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Root_Cause_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Root Cause</value>
            </filterItems>
            <filterItems>
                <field>UIP_Element__c.UIP__c</field>
                <operation>equals</operation>
                <valueField>$Source.UIP__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Challenge</relationshipLabel>
        <relationshipName>Challenge</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>UIP Elements</relationshipLabel>
        <relationshipName>UIP_Elements</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Element</label><nameField>
        <label>UIP Element Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Elements</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith><recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Priority Performance Challenge</description>
        <label>Challenge</label>
    </recordTypes></CustomObject>

classes/ChooseUIPTest.cls
@isTest
public class ChooseUIPTest 
{
    static testMethod void myUnitTest() 
    {
        //Insert Custom Setting for Academic Year        
        Academic_Year__c ay = new Academic_Year__c();
        ay.Name = 'Academic Year';
        ay.currentAcademicYrStartDate__c = date.valueOf('2017-08-01');
        ay.currentAcademicYrEndDate__c = date.valueOf('2018-07-31');
        insert ay;
        
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        String rtSchoolId = Schema.SObjectType.UIP__c.getRecordTypeInfosByName().get('School UIP').getRecordTypeId();
		
    	UIP__c u = new UIP__c();
        u.DISTRICT_NAME__c = a.Id;
        u.DIST_NUMBER__c = a.DIST_NUMBER__c;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        u.Is_Version__c = false;
        u.RecordTypeId = rtSchoolId;
    	insert u;
        
        UIP__c ui = new UIP__c();	// Selected UIP
        ui.DISTRICT_NAME__c = a.Id;
        ui.UIP_Annual_CDE_Plan__c = uac.Id;
        ui.Is_Version__c = false;
    	insert ui;
        
        UIP_Contact__c c = new UIP_Contact__c();
        c.Last_Name__c = 'sd';
        c.UIP__c = ui.Id;
        insert c;

        String challengeRT = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Challenge').getRecordTypeId();        
        UIP_Element__c uc = new UIP_Element__c();
        uc.UIP__c = ui.Id;
		uc.RecordTypeId = challengeRT;
        insert uc;
        
        String MISRT = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Major Improvement Strategy').getRecordTypeId();        
        UIP_Element__c um = new UIP_Element__c();
        um.UIP__c = ui.Id;
		um.RecordTypeId = MISRT;
        insert um;
        
        UIP_Element__c ue = new UIP_Element__c();
        ue.UIP__c = ui.Id;
        ue.Challenge_1__c = uc.id;
        insert ue;
        
        String thisYearRT = Schema.SObjectType.Performance_Indicator_Targets__c.getRecordTypeInfosByName().get('This Year\'s Target').getRecordTypeId();
        String nextYearRT = Schema.SObjectType.Performance_Indicator_Targets__c.getRecordTypeInfosByName().get('Next Year\'s Target').getRecordTypeId();
        List <Performance_Indicator_Targets__c> pitList = new List<Performance_Indicator_Targets__c>();
        Performance_Indicator_Targets__c pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = ui.Id;
        pit.RecordTypeId = thisYearRt;
        pitList.add(pit);
        pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = ui.Id;
        pit.Priority_Performance_Challenge_1__c = uc.id;
        pit.RecordTypeId = nextYearRt;
        pitList.add(pit);
        insert pitList;
        
        Performance_Indicator_Notable_Trends__c pint = new Performance_Indicator_Notable_Trends__c();
        pint.UIP__c = ui.Id;
        pint.Priority_Performance_Challenge_1__c = uc.Id;
        pint.Root_Cause_1__c = ue.id;
        insert pint;
        
        Improvement_Action_Step__c ias = new Improvement_Action_Step__c();
        ias.UIP__c = ui.Id;
        ias.School_Year__c = 'Next School Year';
        ias.Start_Date__c = Date.today().addYears(1);
        ias.Root_Cause_1__c = ue.id;
        ias.Major_Improvement_Strategy__c = um.id;
        
        insert ias;
        
        Performance_Indicator_Notable_Trends__c pintt = new Performance_Indicator_Notable_Trends__c();
        pintt.UIP__c = u.Id;
        insert pintt;
        
        Improvement_Action_Step__c iass = new Improvement_Action_Step__c();
        iass.UIP__c = u.Id;
        insert iass;
        
        Implementation_Benchmark__c ib = new Implementation_Benchmark__c();
        ib.UIP__c = ui.Id;
        ib.School_Year__c = 'Next School Year';
        ib.Start_Date__c = date.today().addYears(1);
        ib.Major_Improvement_Strategy__c = um.id;
        insert ib;
        
        BenchMar_AtciontStep__c bmas = new BenchMar_AtciontStep__c();
        bmas.Implementation_Benchmark__c =  ib.id;
        bmas.Improvement_Action_Step__c = ias.id;
        insert bmas;
        
        Addendum__c ad = new Addendum__c();
		ad.UIP__c = ui.id;
        insert ad;
        
        Supporting_Addenda_Forms__c saf = new Supporting_Addenda_Forms__c();
        saf.Addendum__c = ad.id;
        saf.Title_IA_PPC_Proposed_Amount__c= 10;
        insert saf;
        
        ApexPages.currentPage().getParameters().put('id', u.Id);
        
        ChooseUIP ctrl = new ChooseUIP();
        ctrl.getUIPs();
        ctrl.selectedUIP=ui.Id;
        ctrl.CopyValues();
        ctrl.CopyQuestion();
    }
}