objects/Account.object
<CustomObject><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>8</length>
        <type>Text</type>
    </fields><fields>
        <fullName>SCHOOL_NUMBER__c</fullName>
        <label>School Code</label>
        <length>8</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><sharingModel>Private</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Performance_Challenge_Narrative__c</fullName>
        <label>Performance Challenge Narrative</label>
        <length>50000</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Public_Facing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Facing</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Root_Cause_Narrative__c</fullName>
        <label>Root Cause Narrative</label>
        <length>50000</length>
        <type>Html</type>
    </fields><fields>
        <fullName>SCHOOL_NUMBER__c</fullName>
        <label>School Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Target_Reflection__c</fullName>
        <description>Brief reflection on why previous targets were 
met or not met.</description>
        <inlineHelpText>Brief reflection on why previous targets were 
met or not met.</inlineHelpText>
        <label>Target Reflection</label>
        <length>100000</length>
        <type>Html</type>
    </fields><fields>
        <fullName>TextAreaRich_Test__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>ZPIF_UIP_Identidier__c</fullName>
        <label>ZPIF UIP Identidier</label>
        <length>50</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith><recordTypes>
        <fullName>AEC_UIP</fullName>
        <active>true</active>
        <label>AEC UIP</label>
    </recordTypes></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/ZPIF_UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ZPIF_UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Performance_Challenge_Narrative__c</fullName>
        <label>Performance Challenge Narrative</label>
        <length>50000</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Public_Facing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Facing</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Root_Cause_Narrative__c</fullName>
        <label>Root Cause Narrative</label>
        <length>50000</length>
        <type>Html</type>
    </fields><fields>
        <fullName>SCHOOL_NUMBER__c</fullName>
        <label>School Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Target_Reflection__c</fullName>
        <description>Brief reflection on why previous targets were 
met or not met.</description>
        <inlineHelpText>Brief reflection on why previous targets were 
met or not met.</inlineHelpText>
        <label>Target Reflection</label>
        <length>100000</length>
        <type>Html</type>
    </fields><fields>
        <fullName>TextAreaRich_Test__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipName>ZPIF_UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>ZPIF_UIP_Identidier__c</fullName>
        <label>ZPIF UIP Identidier</label>
        <length>50</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>ZPIF UIP</label><nameField>
        <label>ZPIF UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith><recordTypes>
        <fullName>AEC_UIP</fullName>
        <active>true</active>
        <label>AEC UIP</label>
    </recordTypes></CustomObject>

classes/UIP_MigrateToZPIF_Test.cls
@isTest
public class UIP_MigrateToZPIF_Test 
{
    static testmethod void method1()
    {
        String rType = [Select Id From RecordType  Where SobjectType = 'ZPIF_UIP__c' and DeveloperName = 'AEC_UIP'].Id;
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;
        
        UIP__c u = new UIP__c();
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        u.TextAreaRich_Test__c = 'text';
        u.Root_Cause_Narrative__c = 'text';
        u.Target_Reflection__c = 'text';
        u.Performance_Challenge_Narrative__c = 'text';
        u.Public_Facing__c = true;
        u.SCHOOL_NUMBER__c='123';
        u.DIST_NUMBER__c='123';
        u.ZPIF_UIP_Identidier__c='13';
        insert u;
        
        UIP_MigrateToZPIF.InsertToCache(new List<UIP__c>{u});
    }
}