objects/Account.object
<CustomObject><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>8</length>
        <type>Text</type>
    </fields><fields>
        <fullName>SCHOOL_NUMBER__c</fullName>
        <label>School Code</label>
        <length>8</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><sharingModel>Private</sharingModel></CustomObject>

objects/CDE_Feedback__c.object
<CustomObject><fields>
        <fullName>CDE_Feedback_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDE Feedback Review</label>
        <referenceTo>CDE_Feedback_Review__c</referenceTo>
        <relationshipLabel>CDE Feedback</relationshipLabel>
        <relationshipName>CDE_Feedback</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Feedback_Question1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback_Question1</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback_Question2</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback_Question3</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback_Question4</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback_Question5</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_Reference__c</fullName>
        <label>Section Reference</label>
        <picklist>
            <picklistValues>
                <fullName>Section III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Addenda</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>CDE Feedback</relationshipLabel>
        <relationshipName>CDE_Feedback</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Worksheet_Reference__c</fullName>
        <label>Worksheet Reference</label>
        <picklist>
            <controllingField>Section_Reference__c</controllingField>
            <picklistValues>
                <fullName>Section III: Step One - Brief Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section III: Step Two - Prior Year Targets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section III: Step Three - Current Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section IV: Action Plans - School Target Setting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section IV: Action Plans - Planning Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section III: Step Four - Trend Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section III: Step Five - Priority Performance Challenges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section III: Step Six - Root Causes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>CDE Feedback</label><nameField>
        <label>CDE Feedback Name</label>
        <type>Text</type>
    </nameField><pluralLabel>CDE Feedback</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/CDE_Feedback_Review__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>CDE Feedback Reviews</relationshipLabel>
        <relationshipName>CDE_Feedback_Reviews</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>CDE Feedback Review</label><nameField>
        <label>CDE Review Feedback Name</label>
        <type>Text</type>
    </nameField><pluralLabel>CDE Feedback Reviews</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>A_TTL_RATING_OFFICIAL__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Priority Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turnaround</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Distinction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Priority Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Turnaround</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Priority Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Turnaround</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>CGP_PLAN_TYPE__c</fullName>
        <label>CGP Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Not a CGP Participating School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CGP Systems Change School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CGP Capacity Building School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CGP Universal Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Diagnostic_Review_Grant_Type__c</fullName>
        <label>Diagnostic Review Grant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Diagnostic Review Grantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Diagnostic Review Grantee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>FOCUS_TYPE__c</fullName>
        <label>Focus Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Feedback_Question1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Investigates the most critical performance areas and prioritizes the most urgent performance challenges;</description>
        <label>Feedback_Question1</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies root causes that explain the magnitude of the performance challenges;</description>
        <label>Feedback_Question2</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies research-based major improvement strategies that have a likelihood to eliminate the root causes</description>
        <label>Feedback_Question3</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Feedback_Question4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presents a well-designed plan for implementing the major improvement strategies to bring about dramatic improvement</description>
        <label>Feedback_Question4</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>SCHOOL_NAME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School UIP</relationshipLabel>
        <relationshipName>UIP1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>SCHOOL_NUMBER__c</fullName>
        <label>School Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>SIS_Grant__c</fullName>
        <description>Title I competitive grant that support implementation of major improvement strategies and action steps identified in the school’s action plan.</description>
        <inlineHelpText>Title I competitive grant that support implementation of major improvement strategies and action steps identified in the school’s action plan.</inlineHelpText>
        <label>SIS Grant Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIS Grantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not an SIS Grantee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_TYPE__c</fullName>
        <label>TIG Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>X21st_Century__c</fullName>
        <description>Competitive grant program authorized under Title IV, Part B of ESEA used to establish or expand community learning centers that provide students with academic enrichment opportunities.</description>
        <inlineHelpText>Competitive grant program authorized under Title IV, Part B of ESEA used to establish or expand community learning centers that provide students with academic enrichment opportunities.</inlineHelpText>
        <label>21st Century Grant</label>
        <picklist>
            <picklistValues>
                <fullName>21st Century Learning Center Grant Awardee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a 21st Century Learning Center Grant Awardee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>usip_READ_type__c</fullName>
        <label>READ Act</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><fields>
        <fullName>Academic_Achievement_Measures_Metrics__c</fullName>
        <label>Academic Achievement Measures / Metrics</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Academic_Growth_Gaps_Median_Growth_Perc__c</fullName>
        <label>Academic Growth Gaps Median Growth %</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Academic_Growth_Median_Growth_Perc__c</fullName>
        <label>Academic Growth Median Growth %</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>April_Deadline__c</fullName>
        <label>Final Submission</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Blank_Template_Released__c</fullName>
        <label>Blank Template Released</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Disaggregated_Grad_Rate_Expectation__c</fullName>
        <label>Disaggregated Grad Rate Expectation</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Dropout_Rate_Expectation__c</fullName>
        <label>Dropout Rate Expectation</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Graduation_Rate_Expectation__c</fullName>
        <label>Graduation Rate Expectation</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>January_Deadline__c</fullName>
        <label>Required Review Submission</label>
        <type>Date</type>
    </fields><fields>
        <fullName>October_Deadline__c</fullName>
        <label>Optional Review Submission</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Section_1_Data_Populated__c</fullName>
        <label>Section I Data Populated</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Section_1_Update__c</fullName>
        <label>Section I Update</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/Comments.cls
public without sharing class Comments {
    public String currentId { get; set; }
    public UIP__c uip { get; set; }
    public CDE_Feedback_Review__c cdeFeedbackRev { get; set; }
    public List<CDE_Feedback_Review__c> cdeFeedbackRevList { get; set; }
    public List<CDE_Feedback__c> cdeFeedbackList { get; set; }
    public Map<Id, List<CDE_Feedback__c>> cdeFeedbackMap { get; set; }
    public boolean isfeedback { get; set; }
    public Integer feedbackNumber { get; set; }
    public Integer feedbackCount { get; set; }
    
    public String activeMenu { get; set; }
    public String activeSubMenu { get; set; }
    public boolean isCommunityUser { get; set; }
    
    public String timeline{get;set;}
    public String timeline1{get;set;}
    public String timeline2{get;set;}
    public String timeline3{get;set;}
    public String timeline4{get;set;}
    
    public Boolean fbq1True{get;set;}
    public Boolean fbq1False{get;set;}
    public Boolean fbq2True{get;set;}
    public Boolean fbq2False{get;set;}
    public Boolean fbq3True{get;set;}
    public Boolean fbq3False{get;set;}
    public Boolean fbq4True{get;set;}
    public Boolean fbq4False{get;set;}
    public Boolean fbq5True{get;set;}
    public Boolean fbq5False{get;set;}
    
    public Boolean submitForApproval{get;set;}
    public Boolean currentUserFlag{get;set;}
    public Boolean recordUnderApproval{get;set;}
    public Boolean approvedFlag{get;set;}
    public List<CDE_Feedback__c> cdeFeedbackListofUIP { get; set; }
    public CDE_Feedback__c feedbackOfCurrentYear { get; set; }
    public CDE_Feedback__c feedbackOfLastYear { get; set; }
    
    public void popuateSummaryFeedbackTable()
    {
        if(fbq1True==True)
        {
            feedbackOfCurrentYear.Feedback_Question1__c=true;
            fbq1True=false;
            fbq1False=false;
        }
        if(fbq1False==True)
        {
            feedbackOfCurrentYear.Feedback_Question1__c=false;
            fbq1True=false;
            fbq1False=false;
        }
        if(fbq2True==True)
        {
            feedbackOfCurrentYear.Feedback_Question2__c=true;
            fbq2True=false;
            fbq2False=false;
        }
        if(fbq2False==True)
        {
            feedbackOfCurrentYear.Feedback_Question2__c=false;
            fbq2True=false;
            fbq2False=false;
        }
        if(fbq3True==True)
        {
            feedbackOfCurrentYear.Feedback_Question3__c=true;
            fbq3True=false;
            fbq3False=false;
        }
        if(fbq3False==True)
        {
            feedbackOfCurrentYear.Feedback_Question3__c=false;
            fbq3True=false;
            fbq3False=false;
        }
        if(fbq4True==True)
        {
            feedbackOfCurrentYear.Feedback_Question4__c=true;
            fbq4True=false;
            fbq4False=false;
        }
        if(fbq4False==True)
        {
            feedbackOfCurrentYear.Feedback_Question4__c=false;
            fbq4True=false;
            fbq4False=false;
        }
        if(fbq5True==True)
        {
            feedbackOfCurrentYear.Feedback_Question5__c=true;
            fbq5True=false;
            fbq5False=false;
        }
        if(fbq5False==True)
        {
            feedbackOfCurrentYear.Feedback_Question5__c=false;
            fbq5True=false;
            fbq5False=false;
        }
        Upsert feedbackOfCurrentYear;
        
    }
    
    public void populateTimeLine()
    {
        if(timeline=='none')
        {
            timeline1='';
            timeline2='';
            timeline3='';
            timeline4='';
        }
        if(timeline=='value1')
        {
            timeline1='April 15, 2016';
            timeline2='Submit most current version of UIP to CDE for public posting on SchoolView.';
            timeline3='June 30, 2016';
            timeline4='Submit UIP to CDE for additional review to ensure that required changes were addressed.';
        }
        else if(timeline=='value2')
        {
            timeline1='April 15, 2016';
            timeline2='Submit most current version of UIP to CDE for public posting on SchoolView.';
            timeline3='Jan 15, 2017';
            timeline4='(If applicable) Required changes must be addressed.Jan 15, 2017';
        }
        else if(timeline=='value3')
        {
           timeline1='April 15, 2016';
           timeline2='Submit most current version of UIP to CDE for public posting on SchoolView.';
           timeline3='';
           timeline4='';
        }
        
    }
    
    public Comments() {
    System.debug('In Constructor');
        activeMenu = SectionUtil.setActiveMenu();
        activeSubMenu = SectionUtil.setActiveSubMenu();
        isCommunityUser = SectionUtil.isCommunityUser();
        
        Map<String,String> params = ApexPages.currentPage().getParameters();
        currentId = params.get('id');
        
        if (params.containsKey('feedback')) {
            feedbackNumber = Integer.valueOf(params.get('feedback'));
        } else {
            feedbackNumber = 1;
        }
        selectUIP();
        selectCdeFeedbackRev();
        
        feedbackCount = cdeFeedbackRevList.size();
        if (feedbackCount > 0) {
            isfeedback = true;
            cdeFeedbackRev = cdeFeedbackRevList[feedbackNumber - 1];
            cdeFeedbackList = [SELECT Id, Name, Comments__c, Section_Reference__c, Worksheet_Reference__c, UIP__c, CDE_Feedback_Review__c FROM CDE_Feedback__c WHERE CDE_Feedback_Review__c IN :cdeFeedbackRevList];
            cdeFeedbackMap = new Map<Id, List<CDE_Feedback__c>>();
            
            for (CDE_Feedback__c c : cdeFeedbackList) {
                if (!cdeFeedbackMap.containsKey(c.CDE_Feedback_Review__c)) {
                    cdeFeedbackMap.put(c.CDE_Feedback_Review__c, new List<CDE_Feedback__c>());
                }
                cdeFeedbackMap.get(c.CDE_Feedback_Review__c).add(c);
            }
            for (CDE_Feedback_Review__c cr : cdeFeedbackRevList) {
                if (!cdeFeedbackMap.containsKey(cr.Id)) {
                    cdeFeedbackMap.put(cr.Id, new List<CDE_Feedback__c>());
                }
            }
            System.debug('cdeFeedbackMap:::' + cdeFeedbackMap);
        } else {
            isfeedback = false;
        }
        selectCdeFeedback();
        populateTimeLine();
        submitForApproval=true;
        System.debug('****feedbackOfCurrentYear'+feedbackOfCurrentYear);
        checkApproval();
        System.debug('****submitForApproval'+submitForApproval);
    }
    public void checkApproval()
    {
        if(feedbackOfCurrentYear.ID!=null)
        {
            System.debug('****feedbackOfCurrentYear.ID'+feedbackOfCurrentYear.ID);
            List<ProcessInstance> processes=[Select ID,TargetObjectId,Status from ProcessInstance where TargetObjectId=:feedbackOfCurrentYear.ID];
            System.debug('Process:'+processes);
            if(processes.size()!=0)
            {
                for(ProcessInstance p:processes)
                {
                    System.debug('****p.status'+p.status);
                    if(p.status=='Pending')
                    {
                        submitForApproval=false;
                        recordUnderApproval=true;
                        System.debug('*****recordUnderApproval*****'+recordUnderApproval);
                        List<ProcessInstanceWorkitem> workitems = [select id,actorid,ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstanceId=:p.id];
                        if(workitems.size()!=0)
                        {
                            System.debug('workitems[0].actorId:'+workitems[0].actorId);
                            System.debug('Userinfo.getUserId():'+Userinfo.getUserId());
                            if(Userinfo.getUserId()==workitems[0].actorId)
                                currentUserFlag=true;
                        }
                    }
                    if(p.status=='Approved')
                    {
                       approvedFlag=true; 
                    }
                }
            }
        }
    }
    public void selectUIP() {
        String soql = 'SELECT FOCUS_TYPE__c, Diagnostic_Review_Grant_Type__c, SIS_Grant__c, X21st_Century__c, CGP_PLAN_TYPE__c, usip_READ_type__c, A_TTL_RATING_OFFICIAL__c, TIG_TYPE__c, SCHOOL_NUMBER__c ';
        soql += ', SCHOOL_NAME__r.Name, SCHOOL_NAME__r.SCHOOL_NUMBER__c,DISTRICT_NAME__r.Name,  DISTRICT_NAME__r.DIST_NUMBER__c,UIP_Annual_CDE_Plan__r.April_Deadline__c, UIP_Annual_CDE_Plan__r.Blank_Template_Released__c, UIP_Annual_CDE_Plan__r.January_Deadline__c, UIP_Annual_CDE_Plan__r.October_Deadline__c, UIP_Annual_CDE_Plan__r.Section_1_Data_Populated__c, UIP_Annual_CDE_Plan__r.Section_1_Update__c, RecordType.Name ';
        soql += ', UIP_Annual_CDE_Plan__r.Academic_Achievement_Measures_Metrics__c, UIP_Annual_CDE_Plan__r.Academic_Growth_Median_Growth_Perc__c, UIP_Annual_CDE_Plan__r.Academic_Growth_Gaps_Median_Growth_Perc__c, UIP_Annual_CDE_Plan__r.Graduation_Rate_Expectation__c, UIP_Annual_CDE_Plan__r.Disaggregated_Grad_Rate_Expectation__c, UIP_Annual_CDE_Plan__r.Dropout_Rate_Expectation__c, UIP_Annual_CDE_Plan__r.Mean_CO_ACT_Composite_Score_Expecation__c, UIP_Annual_CDE_Plan__r.Plan_Type_Assignment_ID_Process__c, UIP_Annual_CDE_Plan__r.Title_I_Focus_School_ID_Process__c, UIP_Annual_CDE_Plan__r.TIG_ID_Process__c, UIP_Annual_CDE_Plan__r.CGP_ID_Process__c ';
        soql += ' FROM UIP__c WHERE Id = \'' + currentId + '\'';
        uip = Database.query(soql);
        System.debug('uip:::' + uip);
    }
    
    public void selectCdeFeedbackRev() {
        String soql = SectionUtil.getFieldsQuery('CDE_Feedback_Review__c');
        soql += ' FROM CDE_Feedback_Review__c WHERE UIP__c = \'' + currentId + '\' order by Review_Period__c';
        cdeFeedbackRevList = Database.query(soql);
        System.debug('cdeFeedbackRevList:::' + cdeFeedbackRevList);
    }
    
    Integer year=Date.Today().year();
    public void selectCdeFeedback() 
    {
        
        List<String> yearList=new List<String>();
        //feedbackOfCurrentYear=new CDE_Feedback__c();
        yearList.add(String.valueOf(year));
        yearList.add(String.valueOf(year-1));
        String soql = SectionUtil.getFieldsQuery('CDE_Feedback__c');
        soql += ',Level1_Approver__r.id FROM CDE_Feedback__c WHERE UIP__c = \'' + currentId + '\' AND Feedback_Year__c IN:yearList';
        cdeFeedbackListofUIP = Database.query(soql);
        System.debug('Test CDE:'+cdeFeedbackListofUIP);
        for(CDE_Feedback__c c:cdeFeedbackListofUIP)
        {
            if(c.Feedback_Year__c == String.valueOf((year-1)))
            {
                feedbackOfLastYear=c;
            }
            if(c.Feedback_Year__c == String.valueOf(year))
            {
                feedbackOfCurrentYear=c;
            }
        }
        if(feedbackOfCurrentYear==null)
        {
            feedbackOfCurrentYear=new CDE_Feedback__c(); 
        } 
        
    }
    
    public void saveCurrentFeedback()
    {
       if(feedbackOfCurrentYear.UIP__c==null)
        {
            //feedbackOfCurrentYear=new CDE_Feedback__c();
            feedbackOfCurrentYear.Feedback_Year__c=String.valueOf(year);
            feedbackOfCurrentYear.UIP__c=currentId;
            system.debug('****feedbackOfCurrentYear****'+feedbackOfCurrentYear);
            system.debug('****currentId****'+currentId);
            system.debug('****year****'+String.valueOf(year));
            upsert feedbackOfCurrentYear;
        }
        else
        {
            update feedbackOfCurrentYear;
        }
    }
    public boolean displayPopup {get; set;}
    public void populateApprovers()
    {
        displayPopup = true;
    }
    public void submit() 
    {
        if(feedbackOfCurrentYear.ID!=null)
        {
            feedbackOfCurrentYear.SubmitFlag__c=true;
             update feedbackOfCurrentYear;
        }
    }
    public void submitReq()
    {
        //dc.Level1_Approver__c='005900000033XNP';
        update feedbackOfCurrentYear;
        Approval.ProcessSubmitRequest req=new Approval.ProcessSubmitRequest();
        req.setObjectId(feedbackOfCurrentYear.id);
        Approval.ProcessResult result =Approval.process(req);
        submitForApproval=false;
    }
    public ID getWorkItemId()
    {
        Id retVal = null;
        if(feedbackOfCurrentYear.ID!=null)
        {
            ProcessInstanceWorkitem workItem =[Select Id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId =: feedbackOfCurrentYear.ID];
            retVal =workitem.id;
        }
        return retVal;
    }
    public void approveReq()
    {
        if(feedbackOfCurrentYear.ID!=null)
        {
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('Approve request');
            req.setAction('Approve');
            //req.setNextApproverIds(new Id[] {feedbackOfCurrentYear.Level1_Approver__r.id});
            req.setWorkitemId(getWorkItemId());
            Approval.ProcessResult result =  Approval.process(req);
            recordUnderApproval=false;
            currentUserFlag=false;
            checkApproval();
            
        }
    }
    public void rejectReq()
    {
        if(feedbackOfCurrentYear.ID!=null)
        {
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('Rejected request');
            req.setAction('Reject');
            req.setWorkitemId(getWorkItemId());
            Approval.ProcessResult result =  Approval.process(req);
            recordUnderApproval=false;
            currentUserFlag=false;
            checkApproval();
            
           
        }
    }
}