objects/Account.object
<CustomObject><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>8</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><sharingModel>Private</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>A_TTL_RATING_OFFICIAL__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Priority Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turnaround</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Distinction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Priority Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited with Turnaround</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Priority Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEC: Turnaround</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>DIST_NUMBER__c</fullName>
        <label>Organization Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>ESEA__c</fullName>
        <label>ESEA</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Gifted_Education__c</fullName>
        <label>Gifted Education</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>SCHOOL_NAME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School UIP</relationshipLabel>
        <relationshipName>UIP1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Section_1_Percent_Complete__c</fullName>
        <label>Section I Percent Complete</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Section_1__c</fullName>
        <label>Section I</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Section_2_Percent_Complete__c</fullName>
        <label>Section 2 Percent Complete</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Section_2__c</fullName>
        <label>Section II</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Section_3_Percent_Complete__c</fullName>
        <label>Section 3 Percent Complete</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Section_3__c</fullName>
        <label>Section III</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Section_4_Percent_Complete__c</fullName>
        <label>Section 4 Percent Complete</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Section_4__c</fullName>
        <label>Section IV</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Section_III_Data_Narrative_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when the Data Narrative is complete.</inlineHelpText>
        <label>Section III Data Narrative Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_III_Worksheet_1_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Worksheet 1 is complete.</inlineHelpText>
        <label>Section III Brief Description Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_III_Worksheet_2_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Worksheet 2 is complete.</inlineHelpText>
        <label>Section III Prior Targets Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_II_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Section II is complete.</inlineHelpText>
        <label>Section II Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Student_Grad_Completion_Plan__c</fullName>
        <label>Student Grad Completion Plan</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Closure_Percent_Complete__c</fullName>
        <label>TIG - Closure Percent Complete</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TIG_Closure__c</fullName>
        <label>TIG - Closure</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Restart_Percent_Complete__c</fullName>
        <label>TIG - Restart Percent Complete</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TIG_Restart__c</fullName>
        <label>TIG - Restart</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Transformation_Percent_Complete__c</fullName>
        <label>TIG - Transformation Percent Complete</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TIG_Transformation__c</fullName>
        <label>TIG - Transformation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Turnaround_Percent_Complete__c</fullName>
        <label>TIG - Turnaround Percent Complete</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TIG_Turnaround__c</fullName>
        <label>TIG - Turnaround</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title_1_Percent_Complete__c</fullName>
        <label>Title I School Wide Percent Complete</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Title_1_School_Wide__c</fullName>
        <label>Title I School Wide</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title_III__c</fullName>
        <label>Title III</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Turnaround_Percent_Complete__c</fullName>
        <label>Turnaround Percent Complete</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Turnaround__c</fullName>
        <label>Turnaround</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><fields>
        <fullName>April_Deadline__c</fullName>
        <label>Final Submission</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Blank_Template_Released__c</fullName>
        <label>Blank Template Released</label>
        <type>Date</type>
    </fields><fields>
        <fullName>January_Deadline__c</fullName>
        <label>Required Review Submission</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Next_School_Year__c</fullName>
        <inlineHelpText>Please add the values for next school year (eg 2015-2016)</inlineHelpText>
        <label>Next School Year</label>
        <length>9</length>
        <type>Text</type>
    </fields><fields>
        <fullName>October_Deadline__c</fullName>
        <label>Optional Review Submission</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Section_1_Data_Populated__c</fullName>
        <label>Section I Data Populated</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Section_1_Update__c</fullName>
        <label>Section I Update</label>
        <type>Date</type>
    </fields><fields>
        <fullName>This_School_Year__c</fullName>
        <inlineHelpText>Please put in the dates for this school year (eg 2014-2015)</inlineHelpText>
        <label>This School Year</label>
        <length>9</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/RTFPage.cls
public without sharing class RTFPage {
    public String currentId { get; set; }
    public UIP__c uip { get; set; }
    public String target { get; set; }
    public boolean closeWindow { get; set; }
    public boolean closeReflexionWindow { get; set; }
    
    public RTFPage() {
        system.debug('params::' + ApexPages.currentPage().getParameters().get('target'));
        currentId = ApexPages.currentPage().getParameters().get('id');
        target = EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('target'), 'UTF-8');
        system.debug('target:::' + target);
        selectUIP();
    }
    
    public void selectUIP() {
        uip = [SELECT Id, Name, Turnaround__c, TIG_Turnaround__c, TIG_Transformation__c, Section_1__c, Section_1_Percent_Complete__c, ESEA__c, Gifted_Education__c, Student_Grad_Completion_Plan__c, Title_III__c,
               Section_2__c, Section_2_Percent_Complete__c, Section_3__c, Section_3_Percent_Complete__c, Section_4__c, Section_4_Percent_Complete__c, DIST_NUMBER__c, 
               TIG_Restart__c, TIG_Closure__c, TIG_Transformation_Percent_Complete__c, TIG_Closure_Percent_Complete__c, Turnaround_Percent_Complete__c, 
               TIG_Restart_Percent_Complete__c, TIG_Turnaround_Percent_Complete__c, Title_1_School_Wide__c, Title_1_Percent_Complete__c,
               SCHOOL_NAME__r.Name, City__c, DISTRICT_NAME__r.Name, A_TTL_RATING_OFFICIAL__c,
               UIP_Annual_CDE_Plan__c, UIP_Annual_CDE_Plan__r.April_Deadline__c, UIP_Annual_CDE_Plan__r.Blank_Template_Released__c, 
               UIP_Annual_CDE_Plan__r.January_Deadline__c, UIP_Annual_CDE_Plan__r.October_Deadline__c, 
               UIP_Annual_CDE_Plan__r.Next_School_Year__c, UIP_Annual_CDE_Plan__r.This_School_Year__c,
               UIP_Annual_CDE_Plan__r.Section_1_Data_Populated__c, UIP_Annual_CDE_Plan__r.Section_1_Update__c, RecordType.Name,
               Section_II_Complete__c, Section_III_Worksheet_1_Complete__c, Section_III_Worksheet_2_Complete__c, Section_III_Data_Narrative_Complete__c, Section_IV_Action_Planning_Complete__c, Section_IV_Target_Setting_Complete__c,
               TextAreaRich_Test__c, Target_Reflection__c, TIG_Turnaround_Complete__c, Student_Graduation_and_Completion_Plan__c, TIG_Closure_Complete__c,
               Turnaround_Complete__c, TIG_Transformation_Complete__c, Title_I_School_Wide_Complete__c, Title_III_Complete__c, Gifted_Education_Complete__c, SCHOOL_NUMBER__c,
               ESEA_Complete__c, Student_Grad_Completion_Plan_Complete__c, Narrative_Academic_Achievement_Targets__c, Narrative_Additional__c,
               Narrative_Academic_Growth_Targets__c, Narrative_Academic_Growth_Gaps_Target__c, Narrative_Postsecondary_Workforce_Target__c,
               Narrative_English_Lang_Dev_Attain_Target__c, Narrative_Student_Engagement_Target__c, Performance_Challenge_Narrative__c,
               Root_Cause_Narrative__c, Narrative_Disaggregated_Achievement__c, Narrative_Other__c, Narrative_Student_Behavior__c FROM UIP__c WHERE Id = :currentId];
    }
    
    public void SaveReflexion() {
        System.debug('start:::' + uip.Narrative_Academic_Growth_Targets__c);
        try {
            update uip;
        } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return;
        }
        selectUIP();
        System.debug('end:::' + uip.Target_Reflection__c);
        closeWindow = true;
    }
    
    public void SaveNarrative() {
        try {
            update uip;
        } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return;
        }
        selectUIP();
        closeReflexionWindow = true;
    }
    
    /*public void ClearFormattingNarrative() {
	if (target == 'Academic Achievement (Status)') {
	uip.Narrative_Academic_Achievement_Targets__c= uip.Narrative_Academic_Achievement_Targets__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Academic Growth') {
	uip.Narrative_Academic_Growth_Targets__c= uip.Narrative_Academic_Growth_Targets__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Academic Growth Gaps') {
	uip.Narrative_Academic_Growth_Gaps_Target__c= uip.Narrative_Academic_Growth_Gaps_Target__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Postsecondary & Workforce Readiness') {
	uip.Narrative_Postsecondary_Workforce_Target__c= uip.Narrative_Postsecondary_Workforce_Target__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'English Language Development and Attainment') {
	uip.Narrative_English_Lang_Dev_Attain_Target__c= uip.Narrative_English_Lang_Dev_Attain_Target__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Student Engagement') {
	uip.Narrative_Student_Engagement_Target__c= uip.Narrative_Student_Engagement_Target__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Brief Description') {
	uip.TextAreaRich_Test__c= uip.TextAreaRich_Test__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Current Performance') {
	uip.Target_Reflection__c= uip.Target_Reflection__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Priority Performance Challenges') {
	uip.Performance_Challenge_Narrative__c= uip.Performance_Challenge_Narrative__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Root Causes') {
	uip.Root_Cause_Narrative__c= uip.Root_Cause_Narrative__c.replaceAll('<[^>]+>',' ');
	} else if (target == 'Additional Narrative') {
	uip.Narrative_Additional__c= uip.Narrative_Additional__c.replaceAll('<[^>]+>',' ');
	}
	}*/
    
    public void Cancel() {
        closeWindow = true;
    }
    
    public void CancelNarrative() {
        closeReflexionWindow = true;
    }
}