objects/Addendum__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Addendum</label><nameField>
        <label>Addenda Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Addenda</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Supporting_Addenda_Forms__c.object
<CustomObject><fields>
        <fullName>Addendum__c</fullName>
        <label>Addendum</label>
        <referenceTo>Addendum__c</referenceTo>
        <relationshipName>Supporting_Addenda_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Required ESEA Proposed Budget: 2015-16 Title Funds
This chart must be completed for any district that is accredited with a Priority Improvement or Turnaround plan and accepts ESEA Title funds (i.e., Titles I, IIA, III). The chart must be completed for each applicable Title program.  This includes:
(1)	Title IA Priority Performance Challenge (PPC) activities (10% of district allocation)
(2)	Title IIA activities (entire allocation)
(3)	Title III activities, if the district is a Title III grantee lead (entire allocation)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>ESEA Supporting Addenda Form</label><nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supporting Addenda Forms Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>ESEA_Supporting Addenda Forms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/NewESEAForm.cls
public without sharing class NewESEAForm {
	
	public Supporting_Addenda_Forms__c supAddendum { get; set; }
	private String currentId;
	private String addendumId;
	private String eseaId;
	
	public boolean isNewElem { get; set; }
	public boolean isDeleteError { get; set; }
    public boolean closeWindow { get; set; }
	
	public NewESEAForm() {
		Map<String,String> params = ApexPages.currentPage().getParameters();
		isDeleteError = false;
        closeWindow = false;
		
		if (params.containsKey('id')) {
			currentId = params.get('id');
		}
		if (params.containsKey('addendumId')) {
			addendumId = params.get('addendumId');
		}
		if (params.containsKey('eseaId')) {
			eseaId = params.get('eseaId');
		}
		if (params.containsKey('isNewElem')) {
			isNewElem = boolean.valueOf(params.get('isNewElem'));
		}
		
		selectAddendum();
		
		if (isNewElem) {
			supAddendum = new Supporting_Addenda_Forms__c();
			supAddendum.Addendum__c = addendumId;
		}
	}
	
	public void selectAddendum() {
		if (eseaId != null && eseaId != '') {
			String soql = SectionUtil.getFieldsQuery('Supporting_Addenda_Forms__c');
			soql += ' FROM Supporting_Addenda_Forms__c WHERE Id = \'' + eseaId + '\'';
			supAddendum = Database.query(soql);
		}
	}
	
	public void Save() {
		try {
			upsert supAddendum;
		} catch (DMLException e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));
            return;
		}
        closeWindow = true;
	}
	
	public void DeleteQuestion() {
		isDeleteError = true;
	}
	
	public void DeleteSupAddendum() {
		try {
			delete supAddendum;
		} catch (DMLException e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));
            return;
		}
	}
}