objects/Addendum__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Addenda</relationshipLabel>
        <relationshipName>Addenda</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Addendum</label><nameField>
        <label>Addenda Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Addenda</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Supporting_Addenda_Forms__c.object
<CustomObject><fields>
        <fullName>Addendum__c</fullName>
        <label>Addendum</label>
        <referenceTo>Addendum__c</referenceTo>
        <relationshipName>Supporting_Addenda_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Required ESEA Proposed Budget: 2015-16 Title Funds
This chart must be completed for any district that is accredited with a Priority Improvement or Turnaround plan and accepts ESEA Title funds (i.e., Titles I, IIA, III). The chart must be completed for each applicable Title program.  This includes:
(1)	Title IA Priority Performance Challenge (PPC) activities (10% of district allocation)
(2)	Title IIA activities (entire allocation)
(3)	Title III activities, if the district is a Title III grantee lead (entire allocation)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>ESEA Supporting Addenda Form</label><nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Supporting Addenda Forms Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>ESEA_Supporting Addenda Forms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/NewESEAFormTest.cls
@isTest
public class NewESEAFormTest 
{
    static testMethod void myUnitTest() 
    {
        Account a = new Account();
        a.Name = 'Name';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;
        
        UIP__c u = new UIP__c();
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u;

        Addendum__c add = new Addendum__c();
        add.UIP__c = u.Id;
        insert add;        
        
        Supporting_Addenda_Forms__c sup = new Supporting_Addenda_Forms__c();
        sup.Addendum__c = add.Id;
        insert sup;
        
        
        ApexPages.currentPage().getParameters().put('id', u.Id);
        ApexPages.currentPage().getParameters().put('addendumId', add.Id);
        ApexPages.currentPage().getParameters().put('eseaId', sup.Id);
        ApexPages.currentPage().getParameters().put('isNewElem', 'true');
        
        NewESEAForm ctrl = new NewESEAForm();
        ctrl.Save();
        ctrl.DeleteQuestion();
        ctrl.DeleteSupAddendum();
    }
}