objects/CDE_Feedback__c.object
<CustomObject><fields>
        <fullName>CDE_Feedback_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDE Feedback Review</label>
        <referenceTo>CDE_Feedback_Review__c</referenceTo>
        <relationshipLabel>CDE Feedback</relationshipLabel>
        <relationshipName>CDE_Feedback</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Feedback_Year__c</fullName>
        <label>Feedback Year</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>CDE Feedback</relationshipLabel>
        <relationshipName>CDE_Feedback</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>CDE Feedback</label><nameField>
        <label>CDE Feedback Name</label>
        <type>Text</type>
    </nameField><pluralLabel>CDE Feedback</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/CDE_Feedback_Review__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>CDE Feedback Reviews</relationshipLabel>
        <relationshipName>CDE_Feedback_Reviews</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>CDE Feedback Review</label><nameField>
        <label>CDE Review Feedback Name</label>
        <type>Text</type>
    </nameField><pluralLabel>CDE Feedback Reviews</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/CommentsTest.cls
@isTest
public class CommentsTest 
{
    static testMethod void myUnitTest() 
    {    
        Account a = new Account();
        a.Name = 'Name';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;
        
        UIP__c u = new UIP__c();
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u;
        
        CDE_Feedback__c feedback=new CDE_Feedback__c();
        feedback.UIP__c=u.id;
        feedback.Feedback_Year__c=String.valueOf(Date.Today().year());
        insert feedback;
        
        CDE_Feedback__c feedback1=new CDE_Feedback__c();
        feedback1.UIP__c=u.id;
        feedback1.Feedback_Year__c=String.valueOf((Date.Today().year())-1);
        insert feedback1;
        
        CDE_Feedback_Review__c rev = new CDE_Feedback_Review__c();
        rev.UIP__c = u.Id;
        insert rev;
        
        
        Test.setCurrentPage(Page.Collaboration_Chatter);
        ApexPages.currentPage().getParameters().put('id', u.Id);
        ApexPages.currentPage().getParameters().put('feedback', '1');
        Comments ctrl = new Comments();
        ctrl.timeline='none';
        ctrl.fbq1True=True;
        ctrl.fbq2True=True;
		ctrl.fbq3True=True;
		ctrl.fbq4True=True;
		ctrl.popuateSummaryFeedbackTable();
        ctrl.fbq1False=True;
        ctrl.fbq2False=True;
        ctrl.fbq3False=True;
        ctrl.fbq4False=True;
        ctrl.timeline1='';
        ctrl.timeline2='';
        ctrl.timeline3='';
        ctrl.timeline4='';
        ctrl.currentUserFlag=NULL;
        ctrl.recordUnderApproval=NULL;
        ctrl.approvedFlag=NULL;
        ctrl.popuateSummaryFeedbackTable();
        ctrl.populateApprovers();
        ctrl.submit();
        ctrl.saveCurrentFeedback();

        
        Comments ctrl1 = new Comments();
        ctrl.timeline='none';
        ctrl.populateTimeLine();
        ctrl.timeline='value1';
        ctrl.populateTimeLine();
        ctrl.timeline='value2';
        ctrl.populateTimeLine();
        ctrl.timeline='value3';
        ctrl.populateTimeLine();
        
		delete feedback;
        
        CDE_Feedback__c feedback2=new CDE_Feedback__c();
        feedback2.Feedback_Year__c=String.valueOf(Date.Today().year());
        ctrl.feedbackOfCurrentYear=feedback2;
        ctrl.saveCurrentFeedback();
        try {
        	ctrl.submitReq();
        } catch (Exception ex) {}
        try {
        	ctrl.getWorkItemId();
        } catch (Exception ex) {}
        try {
        	ctrl.approveReq();
        } catch (Exception ex) {}
        try {
        	ctrl.rejectReq();
        } catch (Exception ex) {}
    }
}