objects/Improvement_Action_Step__c.object
<CustomObject><fields>
        <fullName>Root_Cause_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Root Cause</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Improvement Action Steps (Root Cause 1)</relationshipLabel>
        <relationshipName>Improvement_Action_Steps1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Improvement Action Steps</relationshipLabel>
        <relationshipName>Improvement_Action_Steps</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Improvement Action Step</label><nameField>
        <label>Action Step Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Improvement Action Steps</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Performance_Indicator_Notable_Trends__c.object
<CustomObject><fields>
        <fullName>Root_Cause_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause 1</label>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Performance Indicator Notable Trends (Root Cause 1)</relationshipLabel>
        <relationshipName>Performance_Indicator_Notable_TrendsHERJ</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Performance Indicator Notable Trends</relationshipLabel>
        <relationshipName>Performance_Indicator_Notable_Trends</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Performance Indicator Notable Trend</label><nameField>
        <displayFormat>PINNP-{0000}</displayFormat>
        <label>Performance Indicator Notable Trends Nam</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Performance Indicator Notable Trends</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Performance_Indicator_Targets__c.object
<CustomObject><fields>
        <fullName>Major_Improvement_Strategy_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Major Improvement Strategy 1</label>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Performance Indicator Targets (UIP Element)</relationshipLabel>
        <relationshipName>Performance_Indicator_Targets2</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Performance Indicator Targets</relationshipLabel>
        <relationshipName>Performance_Indicator_Targets</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Performance Indicator Targets</label><nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Performance Indicator Targets Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Performance Indicator Targets</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Section_IV_Action_Planning_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Action Planning is complete.</inlineHelpText>
        <label>Section IV Action Planning Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_IV_Target_Setting_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Target Setting is complete.</inlineHelpText>
        <label>Section IV Target Setting Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>TextAreaRich_Test__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Contact__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>UIP Contacts</relationshipLabel>
        <relationshipName>UIP_Contacts</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Junction object between UIP and contacts for Section II of the UIP.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Contact</label><nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>UIP Contact Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>UIP Contacts</pluralLabel><sharingModel>Private</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Element__c.object
<CustomObject><fields>
        <fullName>Major_Improvement_Strategy_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Major Improvement Strategy 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Major Improvement Strategy</value>
            </filterItems>
            <filterItems>
                <field>UIP_Element__c.UIP__c</field>
                <operation>equals</operation>
                <valueField>$Source.UIP__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Challenge 1 (Major Improvement Strategy)</relationshipLabel>
        <relationshipName>Challenge_MIS_1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Root_Cause_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Cause 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>UIP_Element__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Root Cause</value>
            </filterItems>
            <filterItems>
                <field>UIP_Element__c.UIP__c</field>
                <operation>equals</operation>
                <valueField>$Source.UIP__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>UIP_Element__c</referenceTo>
        <relationshipLabel>Challenge</relationshipLabel>
        <relationshipName>Challenge</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>UIP Elements</relationshipLabel>
        <relationshipName>UIP_Elements</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Element</label><nameField>
        <label>UIP Element Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Elements</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith><recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Priority Performance Challenge</description>
        <label>Challenge</label>
    </recordTypes></CustomObject>

classes/UIPHomeControllerTest.cls
@isTest
private class UIPHomeControllerTest 
{ 
    static testMethod void myUnitTest() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        UIP__c u = new UIP__c();
        u.Name = 'Test';
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u;
        
        UIP__c u2 = new UIP__c();
        u2.Name = 'Test ~Final 1';
        u2.DISTRICT_NAME__c = a.Id;
        u2.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u2;
        
        String rtChallengeId = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Challenge').getRecordTypeId();
        String rtMISId = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Major Improvement Strategy').getRecordTypeId();
        String rtRCId = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Root Cause').getRecordTypeId();
        
        List<UIP_Element__c> ueList = new List<UIP_Element__c>();
        //UIP_Element__c ue;
        UIP_Element__c ue = new UIP_Element__c();
        ue.RecordTypeId = rtChallengeId;
        ue.UIP__c = u.Id;
        ueList.add(ue);
        UIP_Element__c ue2 = new UIP_Element__c();
        ue2.RecordTypeId = rtMISId;
        ue2.UIP__c = u.Id;
        ueList.add(ue2);
        UIP_Element__c ue3 = new UIP_Element__c();
        ue3.RecordTypeId = rtRCId;
        ue3.UIP__c = u.Id;
        ueList.add(ue3);
        ue.Root_Cause_1__c = ue2.Id;
        ue2.Major_Improvement_Strategy_1__c = ue3.Id;
        insert ueList;
        //Priority_Performance_Challenge__c ppc = new Priority_Performance_Challenge__c();
        ///ppc.Name = 'PPC Name';
        //insert ppc;
        
        Performance_Indicator_Targets__c pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = u.Id;
        insert pit;
        
        Performance_Indicator_Notable_Trends__c pint = new Performance_Indicator_Notable_Trends__c();
        pint.UIP__c = u.Id;
        insert pint;
        
        Improvement_Action_Step__c ias = new Improvement_Action_Step__c();
        ias.UIP__c = u.Id;
        insert ias;
        
        Attachment att = new Attachment();
        att.Name = 'Test Att';
        att.ParentId = u.id;
        att.Body = Blob.valueOf('Unit Test Attachment Body');
        insert att;
        
        UIP_Contact__c uc = new UIP_Contact__c();
        uc.UIP__c = u.Id;
        Test.setCurrentPage(Page.UIPHome);
        Apexpages.currentPage().getParameters().put('id', u.Id);
        test.startTest();
        UIPHomeController uipc = new UIPHomeController();
        uipc.getForwardTocustomStartPage();
        uipc.getElemRTIds();
        uipc.getNameWithoutVersion('Test');
        uipc.populatePPCTable();
        uipc.produceUIPDoc();
        test.stopTest();
        /*uipc.uip.TextAreaRich_Test__c = 'gfdgsdg';
uipc.uip.Section_IV_Action_Planning_Complete__c = true;
uipc.uip.Section_IV_Target_Setting_Complete__c = true;
uipc.SaveTest();
uipc.submitForSchoolReview();
uipc.submitRecord('V');
uipc.submitForReview();*/
        
    }
    
    static testMethod void myUnitTest4() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        UIP__c u = new UIP__c();
        u.Name = 'Test';
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u;
        
        UIP__c u2 = new UIP__c();
        u2.Name = 'Test ~Final 1';
        u2.DISTRICT_NAME__c = a.Id;
        u2.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u2;
        
        String rtChallengeId = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Challenge').getRecordTypeId();
        String rtMISId = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Major Improvement Strategy').getRecordTypeId();
        String rtRCId = Schema.SObjectType.UIP_Element__c.getRecordTypeInfosByName().get('Root Cause').getRecordTypeId();
        
        List<UIP_Element__c> ueList = new List<UIP_Element__c>();
        UIP_Element__c ue = new UIP_Element__c();
        ue.RecordTypeId = rtChallengeId;
        ue.UIP__c = u.Id;
        ueList.add(ue);
        UIP_Element__c ue2 = new UIP_Element__c();
        ue2.RecordTypeId = rtMISId;
        ue2.UIP__c = u.Id;
        ueList.add(ue2);
        UIP_Element__c ue3 = new UIP_Element__c();
        ue3.RecordTypeId = rtRCId;
        ue3.UIP__c = u.Id;
        ueList.add(ue3);
        ue.Root_Cause_1__c = ue2.Id;
        ue2.Major_Improvement_Strategy_1__c = ue3.Id;
        insert ueList;
        
        Performance_Indicator_Targets__c pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = u.Id;
        insert pit;
        
        Performance_Indicator_Notable_Trends__c pint = new Performance_Indicator_Notable_Trends__c();
        pint.UIP__c = u.Id;
        insert pint;
        
        Improvement_Action_Step__c ias = new Improvement_Action_Step__c();
        ias.UIP__c = u.Id;
        insert ias;
        
        Attachment att = new Attachment();
        att.Name = 'Test Att';
        att.ParentId = u.id;
        att.Body = Blob.valueOf('Unit Test Attachment Body');
        insert att;
        
        UIP_Contact__c uc = new UIP_Contact__c();
        uc.UIP__c = u.Id;
        Test.setCurrentPage(Page.UIPHome);
        Apexpages.currentPage().getParameters().put('id', u.Id);
        
        UIPHomeController uipc = new UIPHomeController();
        uipc.uip.TextAreaRich_Test__c = 'gfdgsdg';
        uipc.uip.Section_IV_Action_Planning_Complete__c = true;
        uipc.uip.Section_IV_Target_Setting_Complete__c = true;
        test.startTest();
        uipc.SaveTest();
        uipc.submitForSchoolReview();
        //uipc.submitRecord('V');
        //uipc.submitForReview();
        test.stopTest();
    }
    
    static testMethod void myUnitTest2() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        UIP__c u = new UIP__c();
        u.Name = 'Test';
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u;
        
        UIP__c u2 = new UIP__c();
        u2.Name = 'Test ~Final 1';
        u2.DISTRICT_NAME__c = a.Id;
        u2.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u2;
        
        UIP_Element__c ue = new UIP_Element__c();
        ue.UIP__c = u.Id;
        insert ue;
        
        //Priority_Performance_Challenge__c ppc = new Priority_Performance_Challenge__c();
        ///ppc.Name = 'PPC Name';
        //insert ppc;
        
        Performance_Indicator_Targets__c pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = u.Id;
        insert pit;
        
        Performance_Indicator_Notable_Trends__c pint = new Performance_Indicator_Notable_Trends__c();
        pint.UIP__c = u.Id;
        insert pint;
        
        Improvement_Action_Step__c ias = new Improvement_Action_Step__c();
        ias.UIP__c = u.Id;
        insert ias;
        
        Attachment att = new Attachment();
        att.Name = 'Test Att';
        att.ParentId = u.id;
        att.Body = Blob.valueOf('Unit Test Attachment Body');
        insert att;
        
        UIP_Contact__c uc = new UIP_Contact__c();
        uc.UIP__c = u.Id;
        Test.setCurrentPage(Page.UIPHome);
        Apexpages.currentPage().getParameters().put('id', u.Id);
        UIPHomeController uipc = new UIPHomeController();
        //ppc = [SELECT Id, Name FROM Priority_Performance_Challenge__c WHERE Id= :ppc.Id];
        //uipc.ppcList = new List<Priority_Performance_Challenge__c>();
        //uipc.rcList = new List<Challenge_Root__c>();
        uipc.getForwardTocustomStartPage();
        //uipc.ppcList.add(ppc);
        uipc.getElemRTIds();
        uipc.getVersion('Test this that ~V3');
        //uipc.getPPCOptions();
        //uipc.getRCOptions();
        uipc.populatePPCTable();
        uipc.produceUIPDoc();
        //uipc.Save();
        //uipc.uip.TextAreaRich_Test__c = 'gfdgsdg';
        //uipc.uip.Section_IV_Action_Planning_Complete__c = true;
        //uipc.uip.Section_IV_Target_Setting_Complete__c = true;
        uipc.SaveTest();
        uipc.submitForSchoolReview();
        uipc.submitForReview();
        
        //uipc.submitRecord('V');
        
        
        UIPHomeController uipc1 = new UIPHomeController(NULL);
        UIPHomeController.TableWrapper t=new UIPHomeController.TableWrapper();
        t.firstColChecked=NULL;
        t.secondColChecked=NULL;
        t.thirdColChecked=NULL;
        t.fourthColChecked=NULL;
        t.fifthColChecked=NULL;
        t.sixthColChecked=NULL;
        t.seventhColChecked=NULL;
        t.eightColChecked=NULL;
        Date s=Date.today();
        Date d=Date.today()+2;
        Date e=Date.today()+4;
        uipc.calculatePrecentCurrentDate(d,s,e);
    }
    
    static testMethod void myUnitTest3() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        UIP__c u = new UIP__c();
        u.Name = 'Test';
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        u.TextAreaRich_Test__c='test';
        u.Section_IV_Action_Planning_Complete__c=true;
        u.Section_IV_Target_Setting_Complete__c=true;
        insert u;
        
        UIP__c u2 = new UIP__c();
        u2.Name = 'Test ~Final 1';
        u2.DISTRICT_NAME__c = a.Id;
        u2.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u2;
        
        UIP_Element__c ue = new UIP_Element__c();
        ue.UIP__c = u.Id;
        insert ue;
        
        Performance_Indicator_Targets__c pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = u.Id;
        insert pit;
        
        Performance_Indicator_Notable_Trends__c pint = new Performance_Indicator_Notable_Trends__c();
        pint.UIP__c = u.Id;
        insert pint;
        
        Improvement_Action_Step__c ias = new Improvement_Action_Step__c();
        ias.UIP__c = u.Id;
        insert ias;
        
        Attachment att = new Attachment();
        att.Name = 'Test Att';
        att.ParentId = u.id;
        att.Body = Blob.valueOf('Unit Test Attachment Body');
        insert att;
        
        UIP_Contact__c uc = new UIP_Contact__c();
        uc.UIP__c = u.Id;
        Test.setCurrentPage(Page.UIPHome);
        Apexpages.currentPage().getParameters().put('id', u.Id);
        
        UIPHomeController uipc = new UIPHomeController();
        uipc.isSchoolUser=true;
        uipc.isDistrictUser=true;
        uipc.isSchoolAdmin=true;
        test.startTest();
        uipc.submitForSchoolReview();
        
		//uipc.submitForReview();
        test.stoptest();
    }
    static testMethod void myUnitTest5() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        UIP__c u = new UIP__c();
        u.Name = 'Test';
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        u.TextAreaRich_Test__c='test';
        u.Section_IV_Action_Planning_Complete__c=false;
        u.Section_IV_Target_Setting_Complete__c=true;
        insert u;
        
        UIP__c u2 = new UIP__c();
        u2.Name = 'Test ~Final 1';
        u2.DISTRICT_NAME__c = a.Id;
        u2.UIP_Annual_CDE_Plan__c = uac.Id;
        insert u2;
        
        UIP_Element__c ue = new UIP_Element__c();
        ue.UIP__c = u.Id;
        insert ue;
        
        Performance_Indicator_Targets__c pit = new Performance_Indicator_Targets__c();
        pit.UIP__c = u.Id;
        insert pit;
        
        Performance_Indicator_Notable_Trends__c pint = new Performance_Indicator_Notable_Trends__c();
        pint.UIP__c = u.Id;
        insert pint;
        
        Improvement_Action_Step__c ias = new Improvement_Action_Step__c();
        ias.UIP__c = u.Id;
        insert ias;
        
        Attachment att = new Attachment();
        att.Name = 'Test Att';
        att.ParentId = u.id;
        att.Body = Blob.valueOf('Unit Test Attachment Body');
        insert att;
        
        UIP_Contact__c uc = new UIP_Contact__c();
        uc.UIP__c = u.Id;
        Test.setCurrentPage(Page.UIPHome);
        Apexpages.currentPage().getParameters().put('id', u.Id);
        
        UIPHomeController uipc = new UIPHomeController();
        uipc.isSchoolUser=true;
        uipc.isDistrictUser=true;
        uipc.isSchoolAdmin=true;
        uipc.submitForSchoolReview();
        uipc.submitForReview();
        uipc.submitRecord('Version');
        uipc.deleteExistingFinalVersion();
        uipc.getNameWithoutVersion('test uschool ~V');
        
        uipc.executiveSummary();
        uipc.downloadPDF();
        uipc.downloadViewPDF();
    }
}