objects/Performance_Indicator_Targets__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>Performance Indicator Targets</relationshipLabel>
        <relationshipName>Performance_Indicator_Targets</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Performance Indicator Targets</label><nameField>
        <displayFormat>PI-{00000000}</displayFormat>
        <label>Performance Indicator Targets Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Performance Indicator Targets</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Element__c.object
<CustomObject><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>UIP Elements</relationshipLabel>
        <relationshipName>UIP_Elements</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Element</label><nameField>
        <label>UIP Element Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Elements</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/RtfControllerTest.cls
@isTest
private class RtfControllerTest 
{
    static testMethod void myUnitTest() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;       
        
        UIP__c uip = new UIP__c();
        uip.DISTRICT_NAME__c = a.Id;
        uip.UIP_Annual_CDE_Plan__c = uac.Id;
        insert uip;
		
		UIP_Element__c uipEl = new UIP_Element__c();
		uipEl.UIP__c = uip.Id;
		insert uipEl;
        
        Performance_Indicator_Targets__c p = new Performance_Indicator_Targets__c();
        p.UIP__c = uip.Id;
        insert p;
        
        ApexPages.CurrentPage().getParameters().put('elemNumber', '1');
        ApexPages.CurrentPage().getParameters().put('elemId', p.Id);
        ApexPages.CurrentPage().getParameters().put('id', uip.Id);
        ApexPages.currentPage().getParameters().put('target','Academic Achievement (Status)');
        
        RtfPage ctrl = new RtfPage();
        ctrl.Cancel();
        ctrl.CancelNarrative();
        ctrl.selectUIP();
        ctrl.SaveReflexion();
        ctrl.SaveNarrative();
        
        //Integer noUip = [SELECT COUNT() FROM UIP__c WHERE Id= :uip.Id];
        
        //System.assertEquals(1, noUip);
    }
}