objects/UIP__c.object
<CustomObject><fields>
        <fullName>DISTRICT_NAME__c</fullName>
        <label>District Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Stat_AddMeas_1_subj1_MeetCutE__c</fullName>
        <label>AS Measure 1 Subject 1 Elem</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Stat_AddMeas_1_subj1_MeetCut_H__c</fullName>
        <label>AS Measure 1 Subject 1 HS</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Stat_AddMeas_1_subj1_MeetCut_M__c</fullName>
        <label>AS Measure 1 Subject 1 MS</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Stat_AddMeas_2_subj1_MeetCutE__c</fullName>
        <label>AS Measure 2 Subject 1 Elem</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Stat_AddMeas_2_subj1_MeetCutH__c</fullName>
        <label>AS Measure 2 Subject 1 HS</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Stat_AddMeas_2_subj1_MeetCutM__c</fullName>
        <label>AS Measure 2 Subject 1 MS</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TARG_E_ACH_PA_PCT_MATH__c</fullName>
        <label>Target Elem Math</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TARG_E_ACH_PA_PCT_READ__c</fullName>
        <label>Target Elem Read</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TARG_H_ACH_PA_PCT_READ__c</fullName>
        <label>Target HS Read</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>TARG_M_ACH_PA_PCT_READ__c</fullName>
        <label>Target MS Read</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>UIP_Annual_CDE_Plan__c</fullName>
        <label>UIP Annual CDE Plan</label>
        <referenceTo>UIP_Annual_CDE_Plan__c</referenceTo>
        <relationshipLabel>UIP</relationshipLabel>
        <relationshipName>UIP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Annual_CDE_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Annual CDE Plan</label><nameField>
        <label>UIP Annual CDE Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP Annual CDE Plans</pluralLabel><sharingModel>ReadWrite</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/UIP_Contact__c.object
<CustomObject><fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields><fields>
        <fullName>UIP__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UIP</label>
        <referenceTo>UIP__c</referenceTo>
        <relationshipLabel>UIP Contacts</relationshipLabel>
        <relationshipName>UIP_Contacts</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Junction object between UIP and contacts for Section II of the UIP.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP Contact</label><nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>UIP Contact Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>UIP Contacts</pluralLabel><sharingModel>Private</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/Section1Test.cls
@isTest
private class Section1Test {

    static testMethod void myUnitTest() 
    {
        Account a = new Account();
        a.Name = 'Test Acc';
        insert a;
        
        UIP_Annual_CDE_Plan__c uac = new UIP_Annual_CDE_Plan__c();
        insert uac;  
        
        UIP__c u = new UIP__c();
        u.DISTRICT_NAME__c = a.Id;
        u.UIP_Annual_CDE_Plan__c = uac.Id;
        u.TARG_E_ACH_PA_PCT_MATH__c = 71;
        u.TARG_H_ACH_PA_PCT_READ__c = 17;
        insert u;
        
        UIP_Contact__c c = new UIP_Contact__c();
        c.Last_Name__c = 'Bob';
        c.UIP__c = u.Id;
        insert c;
        
        ApexPages.currentPage().getParameters().put('contactId', c.Id);
        Apexpages.currentPage().getParameters().put('id', u.Id);
        ApexPages.Standardcontroller stdCtrl = new ApexPages.Standardcontroller(u);
        Section1 s = new Section1(stdCtrl);
        s.newContact();
        s.Save();
        s.selectUIP();
//        s.selectUIPContacts();
        s.showSections();
        s.updateUIP();
        s.DownloadWord_S2();
        s.DownloadExcel_S1();
        s.DownloadExcel_S1_District();
        s.DownloadExcel_S1_AEC();
        s.CancelNewContact();
        ApexPages.currentPage().getParameters().put('editContactId', c.Id);
        s.EditContact();
        s.SaveEditContact();
        s.CancelEditContact();
        s.AddContact();
        s.setPageChanged();
        s.DeleteContact();
        
        
        Integer noUIP = [SELECT COUNT() FROM UIP__c WHERE Id= :u.Id];
        System.assertEquals(1, noUIP);
        
        s.uipPlan = NULL;
		s.selectedContact = NULL;
		u.TARG_E_ACH_PA_PCT_READ__c=100;
		u.TARG_M_ACH_PA_PCT_READ__c=100;
		u.TARG_H_ACH_PA_PCT_READ__c=NULL;
		u.Stat_AddMeas_1_subj1_MeetCut_M__c=100;
		u.Stat_AddMeas_1_subj1_MeetCutE__c=100;
		u.Stat_AddMeas_1_subj1_MeetCut_H__c=100;
		u.Stat_AddMeas_2_subj1_MeetCutE__c=100;
		u.Stat_AddMeas_2_subj1_MeetCutH__c=100;
		u.Stat_AddMeas_2_subj1_MeetCutM__c=100;
        update u;
         s.selectUIP();
		s.showSections();
        
     /*   ApexPages.StandardController stdController = new ApexPages.StandardController(u);
        SectionHeader sh = new SectionHeader(stdController);
        sh.getSection1Map();
        sh.selectAllAddendums();
        sh.getAddendumRTMap(); */
    }
}