objects/UIP__c.object
<CustomObject><fields>
        <fullName>Conga_School_Template_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>xConga School Template Flag</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>ESEA_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ESEA Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>ESEA__c</fullName>
        <label>ESEA</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Gifted_Education_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gifted Education Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Gifted_Education__c</fullName>
        <label>Gifted Education</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Public_Facing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Facing</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is checked if the UIP requires the first review.</description>
        <label>Review Required</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_IV_Action_Planning_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Action Planning is complete.</inlineHelpText>
        <label>Section IV Action Planning Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Section_IV_Target_Setting_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check when Target Setting is complete.</inlineHelpText>
        <label>Section IV Target Setting Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Student_Grad_Completion_Plan_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Student Grad Completion Plan Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Student_Grad_Completion_Plan__c</fullName>
        <label>Student Grad Completion Plan</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Closure_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TIG - Closure Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>TIG_Closure__c</fullName>
        <label>TIG - Closure</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Restart_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TIG - Restart Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>TIG_Restart__c</fullName>
        <label>TIG - Restart</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Transformation_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TIG - Transformation Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>TIG_Transformation__c</fullName>
        <label>TIG - Transformation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TIG_Turnaround_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TIG - Turnaround Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>TIG_Turnaround__c</fullName>
        <label>TIG - Turnaround</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>TextAreaRich_Test__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Title_1_School_Wide__c</fullName>
        <label>Title I School Wide</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title_III_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title III Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Title_III__c</fullName>
        <label>Title III</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title_I_School_Wide_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title I School Wide Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Turnaround_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Turnaround Complete</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Turnaround__c</fullName>
        <label>Turnaround</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>UIP_Status__c</fullName>
        <label>UIP Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit to CDE for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit to CDE for Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received by CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Posting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exercising Biennial Flexibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for District Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Sections and fields for UIP document.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>UIP</label><nameField>
        <label>UIP Name</label>
        <type>Text</type>
    </nameField><pluralLabel>UIP</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/UIPHomeExt.cls
public class UIPHomeExt {
    
    public String currentId { get ; set; }
    public UIP__c uip { get; set; }
    public boolean isCommunityUser { get; set; }
    public boolean isAdminUser { get; set; }
    public boolean isSuccessfullyMsg { get; set; }
    public String ErrorMessage {get;set;}
   
        
    public UIPHomeExt(ApexPages.StandardController stdController) {
                
                currentId = SectionUtil.getUipId();
                System.debug('### uipId =' + currentId);
                uip = [SELECT Turnaround__c, TIG_Turnaround__c, TIG_Transformation__c, Review_Required__c, TIG_Restart__c, TIG_Closure__c, Title_1_School_Wide__c, TextAreaRich_Test__c, ESEA__c, Gifted_Education__c, TIG_Closure_Complete__c, TIG_Transformation_Complete__c, Turnaround_Complete__c, ESEA_Complete__c, Gifted_Education_Complete__c, Title_I_School_Wide_Complete__c, Title_III_Complete__c, TIG_Turnaround_Complete__c, Student_Grad_Completion_Plan__c, Student_Grad_Completion_Plan_Complete__c,Title_III__c, Section_IV_Action_Planning_Complete__c, Section_IV_Target_Setting_Complete__c FROM UIP__c WHERE Id = :currentId];
    }
    
        public UIPHomeExt() {
                
               currentId = SectionUtil.getUipId();
                System.debug('### uipId =' + currentId);
                uip = [SELECT Turnaround__c, TIG_Turnaround__c, TIG_Transformation__c, Review_Required__c, TIG_Restart__c, TIG_Closure__c, Title_1_School_Wide__c, TextAreaRich_Test__c, ESEA__c, Gifted_Education__c, TIG_Closure_Complete__c, TIG_Transformation_Complete__c, Turnaround_Complete__c, ESEA_Complete__c, Gifted_Education_Complete__c, Title_I_School_Wide_Complete__c, Title_III_Complete__c, TIG_Turnaround_Complete__c, Student_Grad_Completion_Plan__c, Student_Grad_Completion_Plan_Complete__c,Title_III__c, Section_IV_Action_Planning_Complete__c, Section_IV_Target_Setting_Complete__c FROM UIP__c WHERE Id = :currentId];
       }
        
        public PageReference submitForSchoolReview() {
                
                // error messages
                String richtextstr = string.valueof(uip.TextAreaRich_Test__c);
                if(richtextstr != null && richtextstr.length() > 0)
                        richtextstr = richtextstr.replaceall('<[^>]+>','');
                if(string.isblank(richtextstr)){
                        ErrorMessage = 'UIP cannot be accepted becuse required elements are missing:  Narrative field must be filled in.';
                        isSuccessfullyMsg = false;
                        return null;
                }
                if(uip.Section_IV_Action_Planning_Complete__c == false) {
                        ErrorMessage = 'UIP cannot be accepted becuse required elements are missing: Action Plan must be complete and ready to submit.';
                        isSuccessfullyMsg = false;
                        return null;
                }
                if(uip.Section_IV_Target_Setting_Complete__c == false) {
                        ErrorMessage = 'UIP cannot be accepted becuse required elements are missing: Target setting must be complete and ready to submit.';
                        isSuccessfullyMsg = false;
                        return null;
                }
                if((uip.TIG_Closure__c == 'Yes' && uip.TIG_Closure_Complete__c == false) || 
                   (uip.TIG_Restart__c == 'Yes' && uip.TIG_Restart_Complete__c == false) || 
                   (uip.TIG_Transformation__c == 'Yes' && uip.TIG_Transformation_Complete__c == false) || 
                   (uip.TIG_Turnaround__c == 'Yes' && uip.TIG_Turnaround_Complete__c == false) || 
                   (uip.Title_1_School_Wide__c == 'Yes' && uip.Title_I_School_Wide_Complete__c == false) || 
                   (uip.Title_III__c == 'Yes' && uip.Title_III_Complete__c == false) || 
                   (uip.Turnaround__c == 'Yes' && uip.Turnaround_Complete__c == false) || 
                   (uip.ESEA__c == 'Yes' && uip.ESEA_Complete__c == false) || 
                   //(uip.Gifted_Education__c == 'Yes' && uip.Gifted_Education_Complete__c == false) || 
                   (uip.Student_Grad_Completion_Plan__c == 'Yes' && uip.Student_Grad_Completion_Plan_Complete__c == false)){
                        ErrorMessage = 'UIP cannot be accepted because required elements are missing:  All addenda must be complete and ready to submit.';
                        isSuccessfullyMsg = false;
                        return null;
                }
                // submitRecord('Final');
                if (uip.Review_Required__c) {
                        uip.Review_Required__c = false;
                }
                uip.Conga_School_Template_Flag__c = true;
                uip.UIP_Status__c = 'Submitted for Posting';
                uip.Public_Facing__c = true;
                Savepoint sp = Database.setSavepoint();
                try {
                    System.debug('uip '+uip);
                    update uip;
                    System.debug('*********uip.Id*********'+uip.Id);
                    Id[] upid = new Id[]{};
                    upid.add(uip.Id);
                    System.debug('upid '+upid);
                    UIP_Cache_Upsert.updateZPIFCachews(upid);   
                } catch (DMLException e) {
                    ErrorMessage = 'Operation Failed:' + e.getMessage() + '(' + e.getStackTraceString() + ')';
                    isSuccessfullyMsg = false;
                    Database.rollback(sp);
                    return null;
                }
                isSuccessfullyMsg = true;
                return null;
        }         
}